GET http://localhost:3000/todos/?priority=HIG
###

GET http://localhost:3000/todos/2
###


GET http://localhost:3000/agenda/?date=2021-2-22
###

POST http://localhost:3000/todos/
Content-Type: application/json

{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "HIGH",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-2-29"
}
###

PUT http://localhost:3000/todos/1/
Content-Type: application/json

{ 
    "status": "DON"
}
###

DELETE http://localhost:3000/todos/1/
###
